services:
  # Serviço 1: Banco de Dados
  postgres:
    image: postgres:14-alpine
    container_name: driva_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - driva_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Serviço 2: n8n
  n8n:
    image: n8nio/n8n
    container_name: driva_n8n
    user: root  
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      # Configuração do Banco Interno do n8n (Onde ele salva workflows)
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}       
      - DB_POSTGRESDB_USER=${POSTGRES_USER}         
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD} 
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - driva_network 

  # Serviço 3: API
  api:
    build: ./api
    container_name: driva_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - API_KEY=${API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - driva_network

  # Serviço 4: Dashboard
  frontend:
    build: ./dashboard
    container_name: driva_dashboard
    restart: always
    volumes:
      - ./dashboard:/app
    ports:
      - "8000:8000"
    environment:
      - "PYTHONUNBUFFERED=1" # Garante que os logs apareçam na hora no seu terminal
      - "DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    # O comando abaixo aplica as tabelas do Django e sobe o servidor
    command: >
      sh -c "python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - driva_network # Vital para ele "enxergar" o serviço 'postgres'

networks:
  driva_network:
    driver: bridge

volumes:
  postgres_data:
  n8n_data: